// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdbtWcnMSYRMsDAJ6wIichjmaxAHQHmzw',
    appId: '1:416186771487:web:39560f5b8f86fca265cd2a',
    messagingSenderId: '416186771487',
    projectId: 'alfinakopi',
    authDomain: 'alfinakopi.firebaseapp.com',
    storageBucket: 'alfinakopi.firebasestorage.app',
    measurementId: 'G-7VBYF661YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkJ_TeTPg4AJegW1H4oHnvaR6_mgNR_h4',
    appId: '1:416186771487:android:b00867838b1aded165cd2a',
    messagingSenderId: '416186771487',
    projectId: 'alfinakopi',
    storageBucket: 'alfinakopi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAkJBoxiSAJUmLH6IveJESODEIO-YwwDU',
    appId: '1:416186771487:ios:ac15c3159a0b04fe65cd2a',
    messagingSenderId: '416186771487',
    projectId: 'alfinakopi',
    storageBucket: 'alfinakopi.firebasestorage.app',
    iosBundleId: 'com.example.latihan1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAkJBoxiSAJUmLH6IveJESODEIO-YwwDU',
    appId: '1:416186771487:ios:ac15c3159a0b04fe65cd2a',
    messagingSenderId: '416186771487',
    projectId: 'alfinakopi',
    storageBucket: 'alfinakopi.firebasestorage.app',
    iosBundleId: 'com.example.latihan1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdbtWcnMSYRMsDAJ6wIichjmaxAHQHmzw',
    appId: '1:416186771487:web:a3eea1960fba106a65cd2a',
    messagingSenderId: '416186771487',
    projectId: 'alfinakopi',
    authDomain: 'alfinakopi.firebaseapp.com',
    storageBucket: 'alfinakopi.firebasestorage.app',
    measurementId: 'G-G6Q6TC2BKS',
  );
}
